name: green-development-planner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - pandas=2.2.1
  - matplotlib=3.8.3
  - jupyterlab=4.1.5
  - seaborn=0.13.2
  - dash=2.16.1
  - dash-bootstrap-components=1.5.0
